apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: game-service
  name: game-service
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8081
  selector:
    io.kompose.service: game-service
